### ISSUE TITLE
Internal Error when Calling with pytest 3.4.1

### ISSUE THREAD

**Issue by zhang-alvin** [aragilar/pytest-mpi#3]
I think this is quite a neat project.

Unfortunately I can't seem to get it to work with my current setup/project. When I call `pytest` (version 3.4.1), I get the following error message:

```
INTERNALERROR> pluggy.PluginValidationError: Plugin 'pytest_mpi' for hook 'pytest_terminal_summary'
INTERNALERROR> hookimpl definition: pytest_terminal_summary(terminalreporter, exitstatus, config)
INTERNALERROR> Argument(s) {'config'} are declared in the hookimpl but can not be found in the hookspec
```

I did a `pip install pytest-mpi` to install. I'm not familiar with these error messages. Is there something obvious that I'm missing or doing wrong?

**Comment by aragilar** [comment]
@zhang-alvin Sorry for not replying before, #5 suggests you need pytest>=4.2 (4.6 apparently is the last pytest that supports python 2.7, if that helps).
